name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Clear the node_modules cache
      - name: Clear cache
        run: rm -rf node_modules

      # Optionally, remove any build directories
      - name: Remove build folder
        run: rm -rf build

      - name: Install dependencies
        run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGRILENS_WEB }}"
          channelId: live
          projectId: agrilens-web
